-- Migration: proposals_migration.sql
-- This file will be appended by scripts/add-missing-proposal-columns.js when missing columns are added.
-- Review before applying on production.

-- Migration generated by scripts/add-missing-proposal-columns.js on 2025-11-05T06:41:26.114Z
ALTER TABLE proposals ADD COLUMN software TEXT DEFAULT NULL;
ALTER TABLE proposals ADD COLUMN duration TEXT DEFAULT NULL;
ALTER TABLE proposals ADD COLUMN site_visit TEXT DEFAULT NULL;
ALTER TABLE proposals ADD COLUMN quotation_validity TEXT DEFAULT NULL;
ALTER TABLE proposals ADD COLUMN mode_of_delivery TEXT DEFAULT NULL;
ALTER TABLE proposals ADD COLUMN revision TEXT DEFAULT NULL;
ALTER TABLE proposals ADD COLUMN exclusions TEXT DEFAULT NULL;
ALTER TABLE proposals ADD COLUMN billing_payment_terms TEXT DEFAULT NULL;
ALTER TABLE proposals ADD COLUMN other_terms TEXT DEFAULT NULL;
ALTER TABLE proposals ADD COLUMN additional_fields TEXT DEFAULT NULL;
ALTER TABLE proposals ADD COLUMN general_terms TEXT DEFAULT NULL;
