-- Create proposals table
CREATE TABLE IF NOT EXISTS proposals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  proposal_number VARCHAR(50) UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL,
  client VARCHAR(255) NOT NULL,
  contact_name VARCHAR(255),
  contact_email VARCHAR(255),
  phone VARCHAR(20),
  project_description TEXT,
  city VARCHAR(100),
  priority ENUM('Low', 'Medium', 'High') DEFAULT 'Medium',
  value DECIMAL(15,2),
  status ENUM('draft', 'pending', 'approved', 'rejected') DEFAULT 'draft',
  due_date DATE,
  notes TEXT,
  lead_id INT,
  
  -- Quotation Fields
  client_name VARCHAR(255),
  client_address TEXT,
  attention_person VARCHAR(255),
  attention_designation VARCHAR(255),
  quotation_no VARCHAR(100),
  date_of_quotation DATE,
  enquiry_no VARCHAR(100),
  date_of_enquiry DATE,
  scope_items JSON,
  amount_in_words TEXT,
  total_amount DECIMAL(15,2),
  gst_number VARCHAR(20),
  pan_number VARCHAR(20),
  tan_number VARCHAR(20),
  terms_and_conditions TEXT,
  payment_mode VARCHAR(100),
  receiver_signature VARCHAR(255),
  company_signature VARCHAR(255),
  signatory_name VARCHAR(255),
  signatory_designation VARCHAR(255),
  
  -- Annexure Fields
  annexure_scope_of_work TEXT,
  annexure_input_documents TEXT,
  annexure_deliverables TEXT,
  annexure_software TEXT,
  annexure_duration TEXT,
  annexure_site_visit TEXT,
  annexure_quotation_validity TEXT,
  annexure_mode_of_delivery TEXT,
  annexure_revision TEXT,
  annexure_exclusions TEXT,
  annexure_billing_payment_terms TEXT,
  annexure_confidentiality TEXT,
  annexure_codes_and_standards TEXT,
  annexure_dispute_resolution TEXT,
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_client (client),
  INDEX idx_status (status),
  INDEX idx_lead_id (lead_id),
  INDEX idx_created_at (created_at)
);